wildfly/wildfly-operator

Gopkg.lock, README.adoc, examples/clustering/README.adoc, examples/postgresql/README.adoc, examples/postgresql/crds/taskrs-app.yaml, pkg/controller/wildflyserver/wildflyserver_controller.go
Update the operator to manage images built with WildFly S2I
(https://github.com/openshift-s2i/s2i-wildfly) instead of the vanilla
WildFly Docker image (https://www.github.com/jboss-dockerfiles/wildfly)
* rename the taskrs example to postgresql
* in the operator,set the jgroups.bind_addr system property to the Pod
IP address to override the property set by the s2i image.
=> Use s2i images

pkg/controller/wildflyserver/wildflyserver_controller.go
WildFly S2I command has been fixed to properly setup the public
interface as well as JGroups bind address.
The Operator no longer needs to overrides the application image command
(which corresponds to
https://github.com/openshift-s2i/s2i-wildfly/blob/master/16.0/s2i/bin/run).
=> Use application image command for the Pods.

pkg/controller/wildflyserver/wildflyserver_controller.go
Annotates resources created by the WildFly Operator with the annotations
recommended by
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
&
https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc
Issue: https://github.com/wildfly/wildfly-operator/issues/4
=> [#4] Use standard annotations

pkg/controller/wildflyserver/wildflyserver_controller.go
Watch secondary resources created by the operator to ensure that any
changes in them will be handle by the reconcile loop.
This fixes #32
=> [#32] Watch operator secondary resources

examples/postgresql/README.adoc, examples/postgresql/crds/taskrs-app.yaml
* update the image to quay.io/jmesnil/taskrs-app:17.0
* update the README as the HTTP route is now created by the operator
when running on OpenShift
=> Update PostgreSQL Example for WildFly S2I 17.0

build/Dockerfile, pkg/controller/wildflyserver/wildflyserver_controller.go
Use the `LABEL_APP_MANAGED_BY` and `LABEL_APP_RUNTIME` to get the values
of the labels put by the operator on the Kubernetes resources.
Set their values in the operator Dockerfile to `wildfly-operator` and
`wildfly`.
This fixes #41.
=> [#41] Externalize labels set by the operator

.travis.yml, Makefile, build/build.sh
* Remove requirement to install operator-sdk to build the project
* Build the project using `go build` directly
* Create the Docker image by executing `docker` directly
The operator-sdk is still required to:
* generate code when the WildFlyServer API changes
* run the e2e and scorecard tests
=> Refactor build process

go.mod, go.sum
Fix location of Apache Thrift as the redirection is not working when
this Operator is built inside Docker.
This fixes #56.
=> [#56] Fix Apache Thrift location

build/Dockerfile, pkg/controller/wildflyserver/wildflyserver_controller.go
use the JBOSS_HOME env var to set the server location to
/opt/jboss/wildfly/ (/wildfly was a symbolic link created for
convenience)
This fixes #55
=> [#55] Fix WildFly directory location

go.mod, go.sum, pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go
Make a DeepEqual check against the statefulset spec env by taking into
account envs added by the operator (for clustering).
Any change to env in the WildFlyServerSpec (add, update, remove) will
trigger an update of the stateful set
Add module github.com/RHsyseng/operator-utils/pkg/utils/openshift to
determine when the operator is running on OpenShift (and skip the
route creation)
Add unit test to check the env update behaviour
This fixes #60
=> [#60] Operator does not update on env removal

pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go
Add `wildfly.org/wildfly-server-generation` annotation to the
statefulset to track the generation of the `WildFlyServer` that created
it.
If the generation does not match, update or delete the `statefulset` so
that its spec will be update according to the latest generation of the
`WildFlyServer`.
This fixes #66
=> [#66] Changes to WildFlyServer Spec are not reflected in StatefulSet

pkg/controller/wildflyserver/wildflyserver_controller.go
fixes #70 
StatefulSet has to be configured to link headless service. Otherwise it does not guarantee DNS identity for pods.
=> [#70] statefulset links headless service instead of loadbalancer

go.mod, go.sum, pkg/controller/util/go_utilities.go, pkg/controller/util/remote_ops.go, pkg/controller/util/wildfly_mgmt.go, pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go
fixes #72 
Fixing the issues found for scaledown processing.
The scaledown could hang in some cases, a panic exception could be got when pod annotations were not ready to be used and a wrong error was reported to the user during processing the finalizer.
=> [issue72] pending container scaledown

pkg/resources/statefulsets/statefulset.go
fixes #70 
The statefulset has to be bound to headless service otherwise it does not guarantees the DNS stability.
=> [#70] statefulset headless service second

pkg/controller/util/go_utilities.go, pkg/controller/util/remote_ops.go, pkg/controller/util/wildfly_mgmt.go, pkg/controller/wildflyserver/transaction_recovery.go, pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go
fixes #76 
fixes #83
The tx-recovery-listener was wrongly checked if it's defined or not. Because of that the scaledown recovery processing was not working properly.
This adds an environmental variable for operator to define socket timeout for transaction scan.
=> [#76] process socket binding read effetively + fixing tx-recovery-listnener checking condition + making the socket timeout configurable

pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go
fixes #82 
transaction recovery will be run only for scaledown but not for `oc delete wildflyserver`
=> [#82] removing transaction recovery finalizers

deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml, doc/apis.adoc, doc/user-guide.adoc, pkg/apis/wildfly/v1alpha1/wildflyserver_types.go, pkg/apis/wildfly/v1alpha1/zz_generated.deepcopy.go, pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go, pkg/controller/util/go_utilities.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go, pkg/resources/constants.go, pkg/resources/statefulsets/statefulset.go
Secrets can be mounted as volumes inside the Pods running the
applications by adding their names to the WildFlyServerSpec.Secrets
field.
Secrets will be mounted under `/etc/secrets/<secret name>`.
This fixes #91.
=> [#91] Support secrets

deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml, doc/apis.adoc, doc/user-guide.adoc, pkg/apis/wildfly/v1alpha1/wildflyserver_types.go, pkg/apis/wildfly/v1alpha1/zz_generated.deepcopy.go, pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go, pkg/resources/constants.go, pkg/resources/statefulsets/statefulset.go
ConfigMaps can be mounted as volumes inside the Pods running the
applications by adding their names to the WildFlyServerSpec.ConfigMaps
field.
ConfigMaps will be mounted under `/etc/configmaps/<config map name>`.
This fixes #92.
=> [#92] Support Config Maps

Makefile
It allows to run the operator locally (instead of deploying it inside
Kubernetes) for development.
=> add run-local-operator make goal

deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml, pkg/apis/wildfly/v1alpha1/wildflyserver_types.go, pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
* minimum value for replicas is 0
* minimum size for Env is 1
* minimum size for EnvFrom is 1
* minimum size for Secrets is 1
* minimum size for ConfigMaps is 1
* PodStatus.State enumarates its valid values
This fixes #101.
=> [#101] Enhance CRD validation

pkg/controller/util/wildfly_mgmt.go, pkg/resources/statefulsets/statefulset.go
The operator will provide the name of the headless service for the S2I script setting up the socket binding client mapping correctly.
=> S2I environmental values for EJB recovery would be setup

pkg/controller/util/remote_ops.go
Just a small fix on adding a timeout for a dead connection during recovery processing.
If the application server would be stuck for some reason it could let handing the connection. The dead timeout defines the time when recovery scan is considered as errorneous and the waiting will be released.
=> Adding socket dial dead timeout when recovery would be stuck

pkg/resources/services/service.go
When updating the route Spec, always copy the clusterIP that was set
after the route was created.
This fixes https://github.com/wildfly/wildfly-operator/issues/117
=> [#117] Avoid uncessary delete of routes

pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/resources/actions.go, pkg/resources/routes/route.go, pkg/resources/services/service.go
It seems there is a time window when a resource is created and when it
is fetched that results in an error.
When creating a resource, catch the AlreadyExists error and requeue the
key so that the reconcile loop will find the existing resource as
expected.
This fixes #120.
=> [#120] Error when resource already exists

README.adoc
as specified in the Custom Resource Definition
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
name: wildflyservers.wildfly.org
```
both `applicationImage` and `replicas` are required as specified here:
```
required:
- applicationImage
- replicas
```
=> updated README.adoc - replicas is a required spec

pkg/controller/util/wildfly_mgmt.go, pkg/controller/wildflyserver/transaction_recovery.go, pkg/resources/constants.go, pkg/resources/statefulsets/statefulset.go, test/framework/wildlfyserver.go
Adding a fix for transaction manager processing being disabled during the scaledown process - aka. no new transaction can be started.
The recovery of existing transaction is still possible (verified with EAP QE testsuite, cc @simkam)
This fix is expected to be follow-up with a broader service stoping during the recovery in future.
fixes #126
=> [#126] disable transaction manager on scale down pod

Makefile
as it will use a specific setup-operator-sdk-e2e-tests.sh to set another
version of the operator-sdk specific for e2e tests
=> Skip setup target for test-e2e-prow

pkg/resources/statefulsets/statefulset.go
Add the image.openshift.io/triggers annotation to the stateful set so
that if an imagestream tag is used for the `applicationImage`, any
changes to the image will trigger a rolling upgrade of the statefulset.
This fixes #27
=> [#27] Support imagestream tag

pkg/controller/util/wildfly_mgmt.go, pkg/controller/wildflyserver/transaction_recovery.go
fix for prior PR: https://github.com/wildfly/wildfly-operator/pull/127
I found I handled wrongly the boolean property as for disabling the transaction manager processing is needed to set to {{true}}.
The default is {{false}} - https://github.com/jbosstm/narayana/blob/5.10.4.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/CoordinatorEnvironmentBean.java#L66
=> [#126] fix on wrong boolean handling, disable transaction manager on scale down

build/Dockerfile
=> [#168] Use ubi8-minimal:latest as the base image

pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
Run make codegen to ensure openapi is generated by the correct
operator-sdk 0.17.2 version
=> Rebuild generated openapi

build/run-minikube.sh, build/run-openshift.sh
…where declaration was put under operator.yaml
As part of the commit for e2e tests for github some yaml declarations were moved under the `operator.yaml`. This should be reflected in the installation shell scripts.
https://github.com/wildfly/wildfly-operator/commit/ef0b424d05f9899e5e476367e2bd3c607c2ef173#diff-b7bd55c11b781b0ccc43aa6e57f9dadf0660e9d1d4e27e0979ee43a407d454ae
=> Fix on sh scripts to not applying removed yaml files

pkg/resources/constants.go, pkg/resources/statefulsets/statefulset.go
If the STATEFULSET_TEMPLATE_LABELS env var contains a JSON
struct, the key and values are added to the labels of the
statefulset's podTemplate
This fixes #197
=> Add labels to the statefulset's template

pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go, pkg/resources/routes/route.go, pkg/resources/services/service.go
The service used to access the statefulset pods is a ClusterIP service
and no longer a LoadBalancer service.
It renamed named with the "-loadbalancer" suffix for backwards
compatibility.
This fixes #213
=> [#213] Create the service as a ClusterIP

deploy/crds/quickstart-resources-cr.yaml, deploy/crds/wildfly.org_wildflyservers_crd.yaml, doc/apis.adoc, doc/user-guide.adoc, pkg/apis/wildfly/v1alpha1/wildflyserver_types.go, pkg/apis/wildfly/v1alpha1/zz_generated.deepcopy.go, pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go, pkg/controller/wildflyserver/wildflyserver_controller.go, pkg/controller/wildflyserver/wildflyserver_controller_test.go, pkg/resources/statefulsets/statefulset.go, test/framework/wildlfyserver.go, version/version.go
* PR which aggregates #210 & #212
=> Operator 0.5.3

deploy/crds/wildfly.org_wildflyservers_crd.yaml, pkg/apis/wildfly/v1alpha1/wildflyserver_types.go, version/version.go
Making this field required prevents to update the Operator with OLM when
there are existing WildFlyServer CR on the cluster.
This change does not impact HPA as this field will be set by the
operator when it manages the WildFlyServer CR
This fixes #221
=> [#221] Do not require .status.selector field

CODEOWNERS, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
=> [issue-241] Update community standards

.github/workflows/go.yml, Makefile
to make the tests run faster as they will not have to pull the images
=> Load wildfly application images in Minikube

controllers/transaction_recovery.go, controllers/wildflyserver_controller.go
All logging should be done through the reconciler  field
=> Update logger calls

go.mod
=> [280] Set 1.20 as minimal Go version

main.go
follows up on #274
Adds also a logger category for the SDK manager
=> [274] Add logger category for the SDK manager

controllers/transaction_recovery.go, pkg/util/wildfly_mgmt.go
Issue [#312](https://github.com/wildfly/wildfly-operator/issues/312) fixed
=> [#312] Wrong detection of heurestic transactions with WildFly 34 Beta
