- README.adoc
add badges to link to Travis CI, Go report card & Zulip.
> Add badges

- pkg/controller/wildflyserver/wildflyserver_controller.go
Create the loadbalancer service before checking that all pods have been
started.
Update the pods status until all have their names and podIP set.
> Fix status update

- Gopkg.lock
- deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml
- doc/apis.adoc
- examples/clustering/README.adoc
- examples/clustering/config/standalone-openshift.xml
- examples/clustering/crds/clusterbench.yaml
- examples/clustering/crds/role_binding.yaml
- pkg/apis/wildfly/v1alpha1/wildflyserver_types.go
- pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
- pkg/controller/wildflyserver/wildflyserver_controller.go
- test/e2e/wildflyserver_test.go
- test/framework/wildlfyserver.go
* Update container command to bind WildFly public address to the pod's
hostname
* Fix spec's Env check
* Add clustering example
> Clustering

- Makefile
- build/Dockerfile
This fixes https://github.com/wildfly/wildfly-operator/issues/21
> [#21] use ubi7/ubi-minimal:latest as the base image

- manifests/wildfly/0.1.0/wildfly-operator.v0.1.0.clusterserviceversion.yaml
- manifests/wildfly/0.1.0/wildfly.crd.yaml
- manifests/wildfly/wildfly.package.yaml
- olm-catalog.Dockerfile
Prepare package for submission of WildFly Operator 0.1.0 to
https://operatorhub.io
> OLM Catalog for WildFly Operator 0.1.0

- manifests/wildfly/0.2.0/wildfly-operator.v0.2.0.clusterserviceversion.yaml
- manifests/wildfly/0.2.0/wildfly.crd.yaml
- manifests/wildfly/wildfly.package.yaml
Prepare package for submission of WildFly Operator 0.2.0 to
https://operatorhub.io
> OLM Catalog for WildFly Operator 0.2.0

- pkg/controller/wildflyserver/wildflyserver_controller.go
Modify the pod container templates to setup liveness/readiness scripts.
If the SERVER_LIVENESS_SCRIPT env var is defined, the operator will use
it to configure an Exec livenessProbe instead of the default HTTP one.
If the SERVER_READINESS_SCRIPT env var is defined, the operator will use
it to configure an Exec readinessProbe. If it not defines, there is no
readiness probe at all.
This fixes #46.
> [#46] Readiness/liveness scripts

- pkg/controller/wildflyserver/wildflyserver_controller.go
This pr to fix  https://github.com/wildfly/wildfly-operator/issues/49
> [#49]Fix update WidlflyServerSpec Env

- pkg/controller/wildflyserver/wildflyserver_controller.go
* Fix the name of the method to errorIsMatchesForKind
This fixes #62.
> [#62] Check for OpenShift Route when watching subresources

- go.sum
- pkg/controller/wildflyserver/transaction_recovery.go
- pkg/controller/wildflyserver/wildflyserver_controller.go
- pkg/controller/wildflyserver/wildflyserver_controller_test.go
- pkg/resources/actions.go
- pkg/resources/constants.go
- pkg/resources/generation.go
- pkg/resources/routes/route.go
- pkg/resources/services/service.go
- pkg/resources/statefulsets/statefulset.go
- vendor/github.com/RHsyseng/operator-utils/LICENSE
- vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
- vendor/github.com/RHsyseng/operator-utils/internal/platform/types.go
- vendor/github.com/RHsyseng/operator-utils/pkg/utils/openshift/utils.go
- vendor/github.com/tevino/abool/.gitignore
- vendor/github.com/tevino/abool/LICENSE
- vendor/github.com/tevino/abool/README.md
- vendor/github.com/tevino/abool/bool.go
- vendor/modules.txt
* Move underlying resources created by the operator in their own packages
(statefulset, services, routes)
* Add actions.go to group CRUD actions on the resources
* Add server generation label to resources that are created/updated
> Refactor resources

- README.adoc
- deploy/crds/quickstart-cr.yaml
- deploy/crds/wildfly_v1alpha1_wildflyserver_cr.yaml
- doc/user-guide.adoc
- examples/clustering/README.adoc
- examples/clustering/crds/clusterbench.yaml
- examples/postgresql/README.adoc
- examples/postgresql/crds/taskrs-app.yaml
- manifests/wildfly/0.1.0/wildfly-operator.v0.1.0.clusterserviceversion.yaml
- manifests/wildfly/0.2.0/wildfly-operator.v0.2.0.clusterserviceversion.yaml
- test/framework/common.go
> [#78] Use quay.io/wildlfy-quickstarts for application images

- deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml
- pkg/controller/util/go_utilities.go
- pkg/controller/util/remote_ops.go
- pkg/controller/util/wildfly_mgmt.go
- pkg/controller/wildflyserver/transaction_recovery.go
- pkg/controller/wildflyserver/wildflyserver_controller.go
- pkg/resources/actions.go
- pkg/resources/services/service.go
- pkg/resources/statefulsets/statefulset.go
Fixes for scaledown to work. These fixes came from issues brought by re-factoring from last days.
Fixes (besides other things) https://issues.jboss.org/browse/WFWIP-215 and operator issues for https://issues.jboss.org/browse/WFWIP-206
> Scaledown recovery fixes

- pkg/controller/wildflyserver/wildflyserver_controller.go
> [#94] Remove hosts when HTTP routes are disabled

- deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml
- doc/apis.adoc
- doc/user-guide.adoc
- pkg/apis/wildfly/v1alpha1/wildflyserver_types.go
- pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
clarify usage of VolumeClaimTemplate.
This fixes #103.
> [#103] Document StorageSpec

- pkg/controller/util/wildfly_mgmt.go
- pkg/controller/wildflyserver/transaction_recovery.go
do not use resource.JBossHome to set the commands executed inside the
application image but rely on the presence of JBOSS_HOME instead
This fixes 112.
> [#112] Use JBOSS_HOME to set the tx recovery script

- pkg/controller/wildflyserver/transaction_recovery.go
just a fix of scale down recovery scan info message that was wrongly formatted and did not show error message properly
> Fix for info message annotation change

- deploy/role.yaml
> [#138] Add permissions to be able to update the deployments/finalizers resource

- build/build.sh
- build/setup-operator-sdk-e2e-tests.sh
- build/setup-operator-sdk.sh
Signed-off-by: Amit Baheti aramswar@in.ibm.com
> Adding support for IBM POWER(ppc64le)

- deploy/role.yaml
> [#159] Fix problem creating ServiceMonitor for Metrics

- manifests/wildfly/0.4.0/wildfly-operator.v0.4.0.clusterserviceversion.yaml
- manifests/wildfly/0.4.0/wildflyservers.wildfly.org.crd.yaml
- manifests/wildfly/wildfly.package.yaml
> Add manifests for WildFly Operator 0.4.0 release

- Makefile
- build/setup-operator-sdk-e2e-tests.sh
- deploy/crds/wildfly.org_wildflyservers_crd.yaml
- pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
> Revert to apiextensions.k8s.io/v1beta1

- doc/user-guide.adoc
> Update doc to mention using imagestream tag

- .gitignore
- Makefile
- build/Dockerfile
- deploy/crds/quickstart-bootable-jar-cr.yaml
- deploy/crds/wildfly.org_wildflyservers_crd.yaml
- doc/apis.adoc
- doc/user-guide.adoc
- pkg/apis/wildfly/v1alpha1/wildflyserver_types.go
- pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
- pkg/controller/wildflyserver/transaction_recovery.go
- pkg/controller/wildflyserver/wildflyserver_controller.go
- pkg/resources/constants.go
- pkg/resources/statefulsets/statefulset.go
- test/e2e/18.0/wildflyserver_test.go
- test/e2e/bootable-21.0/main_test.go
- test/e2e/bootable-21.0/wildflyserver_test.go
- test/framework/common.go
- test/framework/wildlfyserver.go
> [#166] Integrate Bootable JAR application images

- .github/workflows/go.yml
> Push image to registry when commits are pushed on master

- deploy/crds/wildfly.org_wildflyservers_crd.yaml
- pkg/apis/wildfly/v1alpha1/wildflyserver_types.go
- pkg/apis/wildfly/v1alpha1/zz_generated.openapi.go
> [#170] Update BootableJar description

- version/version.go
> Bump version to 0.5.2

- pkg/resources/services/service.go
> Copy clusterIP when updating services

- pkg/controller/wildflyserver/wildflyserver_controller.go
- pkg/resources/actions.go
>  [#191] fix for scaling up during recovery processing

- pkg/controller/util/remote_ops.go
- pkg/controller/wildflyserver/transaction_recovery.go
- pkg/controller/wildflyserver/transaction_recovery_test.go
- pkg/controller/wildflyserver/wildflyserver_controller_test.go
fixes #202 
@yersan I'm adding some more unit tests of the txn scale down processing.
> [#202] adding new txn scaledown unit tests

- pkg/controller/wildflyserver/transaction_recovery_test.go
- test/framework/common.go
- test/framework/wildlfyserver.go
Fixes #200
@jmesnil Would you mind reviewing and approve in case? thanks!
> [Issue#200] Add persistent storage to make the scale-down e2e test involving transaction recovery

- doc/apis.adoc
After https://github.com/wildfly/wildfly-operator/pull/222
> [Doc] Selector is not required anymore

- version/version.go
> Next version is 0.5.5

- version/version.go
> Next version is 0.5.6

- .github/workflows/go.yml
> Update GitHub Actions

- README.adoc
> Fix outdated route documentation

- api/v1alpha1/wildflyserver_types.go
- config/crd/bases/wildfly.org_wildflyservers.yaml
- go.sum
- pkg/resources/statefulsets/statefulset.go
* Do not specify the 185 (jboss) user by default
> [#266] Updated Pod security standards

- .github/workflows/go.yml
- Dockerfile
- go.mod
- go.sum
> [280] Bump Go version to 1.21.3

- controllers/wildflyserver_controller.go
- pkg/resources/actions.go
- pkg/resources/constants.go
- pkg/resources/statefulsets/statefulset.go
> [285] Fix image stream processing

- main.go
> [289] Use ISO8601 for log timestamps

- controllers/wildflyserver_controller.go
> [291] Cleanup scaled down pod status

- main.go
> [#297] Upgrade leader eleccion lock name

- config/manager/kustomization.yaml
- main.go
> [#301] Replace leader-for-life leader election with leader-for-lease 

- api/v1alpha1/wildflyserver_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/wildfly.org_wildflyservers.yaml
- controllers/transaction_recovery.go
- controllers/transaction_recovery_test.go
- controllers/wildflyserver_controller.go
- doc/apis.adoc
- doc/user-guide.adoc
- pkg/util/wildfly_mgmt.go
This PR addresses #100 and [EAP7-1394](https://issues.redhat.com/browse/EAP7-1394).
> Addressed issue #100 and EAP7-1394

- Makefile
> [#314] Implement a Go version check to limit maximum Go version allowed to build the project

- Dockerfile
> [#324] Use UBI9 and google registry mirror

- .github/workflows/go.yml
- Makefile
- README.adoc
- build/build.sh
- config/tests/build-test-images.sh
- config/tests/kustomization.yaml
- config/tests/patch-image-pull-policy.yaml
- examples/clustering/README.adoc
- test/e2e/suite_test.go
- test/e2e/wildflyserver_test.go
> [#327] Build test images on the fly when running the testsuite

- api/v1alpha1/wildflyserver_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/wildfly.org_wildflyservers.yaml
- controllers/wildflyserver_controller_test.go
- pkg/resources/statefulsets/statefulset.go
> [#329] Align Operator default probes configuration with Helm Charts
